---
   -name: install apache & php &  mysql
    hosts: vagrant
    gather_facts: true


    tasks:
      - name: "install apache2"
        package: name=apache2 state=present
      - name: "install apache2-php"
        package: name=libapache2-mod-php state=present
      - name: "install php-cli"
      - name: "install php-mcrypt"
        package: name=php-mycrypt state=present
      - name: "install php-mysql"
        package: name=php-mysql state=present
      - name: "install mysql-server"
        package: name=mysql-server state=present